# Generated by Django 2.2.12 on 2020-07-13 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited date')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published date')),
                ('cover', models.ImageField(upload_to='photos/')),
                ('author', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=False, to='article.Category')),
            ],
        ),
    ]
